Add more logs and checks
MSO4SC/cloudify-hpc-plugin pull request #70
Opened 2018-06-28 07:48 UTC by Trophime

Add output of scripts to log
Add output of slurm job to log in revert_job
Add a new script for sending slurm output in revert_job
Performs check for valid partitions, valid reservation, valid tasks (ie == nodes*tasks_per_node)

2018-06-28 11:03 UTC, emepetres requested changes
Nice job, interesting changes. This could mean a push forward regarding application logs.

I stopped commenting the code because it is too long. In general seems promising but took me a long time to revise.
Before revising again I propose several changes:
- The code use flake8 linter. Please stick to it. There is a lot of code changed only to put code in one line. This breaks the style and makes the pull request much harder to review.
- The logs are in general too verbose to be added as a general log and seen in the portal by default.
- Commented code must be removed.
- slurm.py has its test class. You have to change the tests according to the new code.
- Code is tested using tox. See the readme.Tests are done simulating the hpc connection, to run an specific test with an hpc, comment the simulate property and use the script run_blueprint_test.sh
- README must be updated accordingly
- The new features as how to retrieve partitions or the job outputs to log should be detailed in the pull request text to better understand the changes.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        if not 'password' in key:
Should be `if key != 'password'`. Also other credentials as the private_key or private_key_password must be masked if present.

Apart from this, I think this should be more a debug log than an info one. In this regard, we should have a mechanism from the portal to decide if we want debug messages or not.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        ctx.logger.info('Loading deployment inputs..')
Again, too verbose logs. I think it should be moved to debug logs.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        ctx.logger.info('Loading credentials..')
Again, too verbose logs. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        ctx.logger.info('getting working credentials..')
Again, too verbose logs. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        ctx.logger.info('script..%s'%name)
Again, too verbose logs. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        ctx.logger.info('workload_manager..')
Again, too verbose logs. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +            ctx.logger.info('revert_job: job_output=%s'%job_output)
Again, too verbose logs. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    ctx.logger.info('Deploying job..')
Again, too verbose logs. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    ctx.logger.info('Creating shell script..')
Again, too verbose logs. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    ctx.logger.info('deploy_job: script=%s'%script)
Again, too verbose logs. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        exit_code = wm.send_notify_user(client,
Notification to a new user should be done in an independent task, and run by the run_jobs workflow when it ends. Here is really notifying the user when a revert is performed.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        # ctx.logger.info('deploy_job: call=%s'%call)
Remove commented code

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +            ctx.logger.info('deploy_job: output=%s'%output)
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    ctx.logger.info("----send_job-----------")
Too verbose. Move to debug.

Remove commented code.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +            logger.info("removing %s"%name)
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +            ctx.logger.info('deploy_job: cmd_out=%s'%cmd_out)
If the log is big, I'm afraid it will degrade the logs user experience.
What correspond to "name" in this case?
Is this the application log?

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    # ctx.logger.info("job_options:" )
Remove commented code.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    is_singularity = 'hpc.nodes.singularity_job' in ctx.node.type_hierarchy
Be carefull with flake8 errors: Is this line too long?

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        ctx.logger.info("----WORKLOAD_MANAGER-----------")
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        ctx.logger.info("----WORKLOAD_MANAGER DONE-----------")
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +        ctx.logger.error('Job ' + name + ' (' + ctx.instance.id + ') not sent.')
Check flake8 errors

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +            ctx.logger.info("send_job: slurm_job_id=%s"%slurm_job_id)
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    ctx.logger.info("----send_job done-----------")
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    ctx.logger.info("----cleanup_job-----------")
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    ctx.logger.info('------stop_job------')
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/tasks.py
> +    ctx.logger.info('------publish------')
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workflows.py
> +        # print "queue_all_instances"
Remove commented code

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workflows.py
> +    ctx.logger.info(
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workflows.py
> +    # for i,root in enumerate(root_nodes):
Remove commented code

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workflows.py
> +    ctx.logger.info(
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workflows.py
> +            ctx.logger.info("node_name=%s status=%s"%(str(node_name), status))
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workflows.py
> +    # print "end while loop"
Remove commented code

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        if self.check_job_settings_key(job_settings, 'stderr_file'):
check flake8 errors, line probably to long

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            _settings += _prefix + ' -e ' + str(job_settings['stderr_file']) + _suffix
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            _settings += _prefix + ' -e ' + str(job_id + '.err') + _suffix
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            _settings += _prefix + ' -o ' + str(job_settings['stdout_file']) + _suffix
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            _settings += _prefix + ' -e ' + str(job_id + '.out') + _suffix
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            _settings += _prefix + ' -t ' + str(job_settings['max_time']) + _suffix
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            _settings += _prefix + ' -p ' +  str(job_settings['partition']) + _suffix
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            _settings += _prefix + ' -N ' +  str(job_settings['nodes']) + _suffix
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        # logger.info("settings=%s"%_settings)
Remove commented code

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        logger.info("----_slurm: _build_container_script-----------")
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        # logger.info("job_settings:" )
Remove commented code

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        if 'modules' and 'modules' in job_settings:
It should be `If 'modules' in job_settings and job_settings['modules']`

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        # logger.info("script=%s"%script)
Remove commented code

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        if 'mail_user' in job_settings:
`... and job_settings['mail_user']`

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        logger.info("----_slurm: _build_job_submission_call-----------")
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            return {'error': "'type' and 'command' must be defined in job settings"}
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +            return {'error': "Job type '" + job_settings['type'] + "'not supported"}
flake8

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/slurm.py
> +        logger.info("_build_job_submission_call: parse_slurm_job_settings")
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on hpc_plugin/workload_managers/workload_manager.py
> +        logger.info("----WORKLOAD_MANAGER: SUBMIT_JOB-----------")
Too verbose. Move to debug.

2018-06-28 11:03 UTC, emepetres commented on plugin.yaml
> +        source: https://github.com/Trophime/cloudify-hpc-plugin/archive/add_checks.zip
move to canary again before merge

2018-06-29 08:12 UTC, emepetres commented on dev-requirements.txt
> +https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/4.3.1.zip
We are using the community version of cloudify, please revert

2018-06-29 08:13 UTC, emepetres commented
Tests failed. The best practice would be to run tox in your computer and ensure that all tests are passing before pushing the changes.

2018-06-29 08:23 UTC, Trophime commented
@emepetres could you help with the test. I don't understand what's going on..

2018-06-29 08:45 UTC, emepetres commented
Do you have problems running tox, or understanding its logs?

2018-06-29 08:51 UTC, Trophime commented
actually the test fails because 2 fields have been inverte:
```
module load mod1 mod2; sbatch --parsable -J 'test' -e stderr.out -o stdout.out -t 00:05:00 -p thinnodes -N 4 --ntasks-per-node=24 -n 96 --mem=4GB --reservation=mso4sc --qos=qos --mail-user=user@email.com --mail-type=ALL cmd
module load mod1 mod2; sbatch --parsable -J 'test' -e stderr.out -o stdout.out -t 00:05:00 -p thinnodes -N 4 -n 96 --ntasks-per-node=24 --mem=4GB --reservation=mso4sc --qos=qos --mail-user=user@email.com --mail-type=ALL cmd
```
what shall I do change what is expected or try to understand why the 2 fiels have been inverted?

2018-06-29 10:07 UTC, Trophime commented
now the test pass with py27.

I've psuhed a new version with some improvments
Still I dunno how best to split long lines? Any advices?

As for your comment about adding log and getting partitions what do you like some explanations or separate commits?

2018-06-29 10:18 UTC, Trophime commented
the errro in tox flake8 is due to cloudify:
```
Collecting https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/18.1.11.zip (from -r dev-requirements.txt (line 1))
  Downloading https://github.com/cloudify-cosmo/cloudify-dsl-parser/archive/18.1.11.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ups9gzxq/setup.py", line 29
        except ImportError, e:
                          ^
    SyntaxError: invalid syntax
```
seems like a syntax error in the installer?

2018-06-29 11:51 UTC, Trophime commented
note that flake8 tox test also fails for canary version!!

2018-12-17 15:25 UTC, closed without merging